language: rust
rust:
  - 1.46.0
  - beta
  - nightly
sudo: false
# before_script:
#   - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo build --verbose
#  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
notifications:
  email:
    on_success: never
