[package]
name = "rng"
version = "0.0.1"
authors = ["Christoph <gaoler@electronicpanopticon.com>"]
repository = "https://github.com/folkengine/random_name_generator_rs.git"
homepage = "https://github.com/folkengine/random_name_generator_rs"
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rnglib"
path = "src/lib.rs"

[[bin]]
name = "rng"
path = "src/main.rs"

[dependencies]
regex = "1"